### ISSUE TITLE
[metabug] New codebase

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#2]
# Code
- [x] New common repo
- [x] Cleaner directory structure
- [ ] Platforms
  - [x] [Device platforms](26)
  - [x] [OS platforms](4)
  - [ ] [Merge work in forks](6) (and redirect those repos here if possible)
  - [x] Make it possible to select multiple triggering methods when they are available
  - [x] Refactor and merge @maso27's snowboy implementation
- [x] Common configuration in the config file (no config in `.py` files), maybe YAML
- [ ] [Python 3](7)
- [x] [clean code](21)
# Docs (after the code is stabilized a bit)
- [x] describe in detail things in `CONTRIBUTING.md`
- [x] update Requirements section in `README.md` to include the fact that when installing AlexaPi on a remote headless computer, the user **needs** to also include the URL containing the IP of the machine in _Allowed Return URLs_  in order to later access the auth page
- [x] update Install section in `README.md` after it has been figured out in the new code base
- [x] write a short guide explaining how to go from the old version to the new version
- [ ] update the documentation for developers when all the basic stuff gets settled
# Going public (after the code is stabilized a bit and there is enough docs)
- [x] Invite people to develop with us.
- [x] Invite public to test. 
- [x] When we're confident enough, mark Sam's repo as deprecated and redirect people to our repo.
# Other
- [ ] Use semantic versioning (http://semver.org/) when we're not doing backwards-incompatible changes every day.

**Comment by renekliment** [comment]
@illperipherals Let's move the discussion here so we don't spam that actual issue.

The instructions for Mason were for the older PR that didn't solve the path things so I'm not surprised it didn't work.

CR and testing is exactly what's needed! So if you have any time, please look at #8 and #10. They both received quite some attention already and I think there are no more problems, but I need someone with a final word. Then we can move to the stuff that rocks :-)
Thank you!

**Comment by illperipherals** [comment]
Sounds good.

**Comment by renekliment** [comment]
The original idea of this is done basically. Closing.
