### ISSUE TITLE
[metabug] OS platforms

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#4]
- [x] don't require root when not needed
- [x] install into `/opt`
- [x] universal paths generally (no `/home/pi` or `/root/`, ...)
- [x] [universal init files for all platforms](9)
- [x] [rewrite the setup script](60)

**Comment by renekliment** [comment]
Last part of this fixed by #82.
